/** Словари модуля двора: ключ есть в обоих языках или его нет нигде. */

export const strings = {
  ru: {
    "resource.meat": "Мясо",
    "resource.wood": "Дерево",
    "resource.stone": "Камень",
    "resource.metal": "Металл",
    "resource.mushrooms": "Грибы",
    "resource.gold": "Золото",
    "building.townhall": "Ратуша",
    "building.cottage": "Жилой дом",
    "building.farm": "Ферма",
    "building.sawmill": "Пилорама",
    "building.quarry": "Каменоломня",
    "building.mine": "Рудник",
    "building.barracks": "Казарма",
    "building.lantern": "Фонарь",
    "building.bench": "Скамейка",
    "building.well": "Колодец",
    "building.flag": "Знамя",
    "court.report.welcome": "Двор основан: Ратуша построена",
    "court.report.placed": "Возведена постройка: {building}",
    "court.report.upgraded": "Ратуша улучшена: уровень {level}",
    "court.report.removed": "Постройка убрана: {building}",
  },
  en: {
    "resource.meat": "Meat",
    "resource.wood": "Wood",
    "resource.stone": "Stone",
    "resource.metal": "Metal",
    "resource.mushrooms": "Mushrooms",
    "resource.gold": "Gold",
    "building.townhall": "Town Hall",
    "building.cottage": "Cottage",
    "building.farm": "Farm",
    "building.sawmill": "Sawmill",
    "building.quarry": "Quarry",
    "building.mine": "Mine",
    "building.barracks": "Barracks",
    "building.lantern": "Lantern",
    "building.bench": "Bench",
    "building.well": "Well",
    "building.flag": "Banner",
    "court.report.welcome": "Court founded: Town Hall built",
    "court.report.placed": "Building raised: {building}",
    "court.report.upgraded": "Town Hall improved: level {level}",
    "court.report.removed": "Building removed: {building}",
  },
} as const;

export type CourtStringKey = keyof typeof strings.ru;
